language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버 홈
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle/'

script: "./gradlew clean build"

before_deploy:
  - mkdir -p before-deploy # zip에 포함시킬 파일들을 담을 디렉토리
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp build/libs/*.jar before-deploy/
  - cd before-deploy && zip -r before-deploy * # before-deploy 디렉토리에서 전체 압축
  - cd ../ && mkdir -p deploy # 상위 디렉토리에서 deploy 디렉토리 생성
  - mv before-deploy/before-deploy.zip deploy/server-test.zip # deploy로 zip 파일 이동

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo 설정 값
    secret_access_key: $AWS_SECRET_KEY
    bucket: server-test-travis-bucket
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근 설정
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: server-test-travis-bucket
    key: server-test.zip # 빌드 파일 압축하여 전달

    bundle_type: zip # zip 확장자
    application: server-test # CodeDeploy 애플리케이션
    deployment_group: server-test-group # CodeDeploy 배포 그룹

    region: ap-northeast-2
    wait-until-deployed: true

# CI 실행 완료 시 메일 알람
#notifications:
#  email:
#    recipients:
#      - ozofweird@example.support
